name: Build and Deploy

on:
  push:
    branch: ["alo"]

jobs:
  build:
    name: Web Build with Pnpm
    runs-on: ubuntu-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: "â˜ï¸ Checkout repository"
        uses: actions/checkout@v4

      - name: "ğŸ”§ Setup Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: "ğŸ“¦ Install pnpm && dependencies"
        run: |
          npm install -g pnpm
          pnpm install

      - name: "ğŸ” Lint code"
        run: pnpm lint

      - name: "ğŸ“ Checking code format"
        run: pnpm format:check

      - name: "ğŸš€ Build the project"
        run: pnpm build

      - name: "ğŸ“¤ Scp to tencentyun"
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_ID }}
          key: ${{ secrets.ID_RSA }}
          port: ${{ secrets.HOST_PORT }}
          source: "dist"
          target: "/home/ubuntu"
